create_event:
  name: Create Calendar Event
  description: Creates a new event in the Exchange calendar.
  fields:
    subject:
      name: Subject
      description: The subject of the event.
      example: "Team Meeting"
      required: true
      selector:
        text:
    date_start:
      name: Start Time
      description: The start time of the event in ISO format.
      example: "2025-05-13 10:00:00"
      required: true
      selector:
        datetime: {}
    date_end:
      name: End Time
      description: The end time of the event in ISO format.
      example: "2025-05-13 11:00:00"
      required: true
      selector:
        datetime: {}
    location:
      name: Location
      description: The location of the event.
      example: "Conference Room"
      selector:
        text:
    body:
      name: Body
      description: The body or description of the event.
      example: "Discuss project updates."
      selector:
        text:

delete_event:
  name: Delete Calendar Event
  description: Deletes an event from the Exchange calendar by ID.
  fields:
    event_id:
      name: Event ID
      description: The unique ID of the event to delete.
      example: "AAMkAGI2..."
      required: true
      selector:
        text:

search_event:
  name: Search Calendar Events
  description: Searches for events in the Exchange calendar within a date range.
  fields:
    date_start:
      name: Start Time
      description: The start time of the search range in ISO format.
      example: "2025-05-13 00:00:00"
      required: true
      selector:
        datetime: {}
    date_end:
      name: End Time
      description: The end time of the search range in ISO format.
      example: "2025-05-14 00:00:00"
      required: true
      selector:
        datetime: {}
