exchange_create_event:
  name: Create Calendar Event
  description: Creates a new event in the Exchange calendar.
  fields:
    summary:
      name: Summary
      description: The title of the event.
      required: true
      example: "Team Meeting"
      selector:
        text:
    start:
      name: Start Time
      description: The start time of the event (ISO format, e.g., 2025-05-10T10:00:00Z).
      required: true
      example: "2025-05-10T10:00:00Z"
      selector:
        text:
    end:
      name: End Time
      description: The end time of the event (ISO format, e.g., 2025-05-10T11:00:00Z).
      required: true
      example: "2025-05-10T11:00:00Z"
      selector:
        text:
    description:
      name: Description
      description: Additional details about the event.
      required: false
      example: "Discuss project updates"
      selector:
        text:

exchange_delete_event:
  name: Delete Calendar Event
  description: Deletes an event from the Exchange calendar by its event ID.
  fields:
    event_id:
      name: Event ID
      description: The unique ID of the event to delete.
      required: true
      example: "AAMkAD..."
      selector:
        text:

exchange_search_events:
  name: Search Calendar Events
  description: Searches for events in the Exchange calendar matching a search term.
  fields:
    search_term:
      name: Search Term
      description: The term to search for in event summary or description.
      required: true
      example: "Meeting"
      selector:
        text:
    start:
      name: Start Time
      description: The start of the time range to search (ISO format, e.g., 2025-05-01T00:00:00Z).
      required: false
      example: "2025-05-01T00:00:00Z"
      selector:
        text:
    end:
      name: End Time
      description: The end of the time range to search (ISO format, e.g., 2025-05-31T23:59:59Z).
      required: false
      example: "2025-05-31T23:59:59Z"
      selector:
        text:
